### ISSUE TITLE
Injecting stateful service instance into controller/middleware question

### ISSUE THREAD

**Issue by rktect** [toddabel/service-fabric-watchdog#1]
Hi Todd,

I must thank you for posting your Service Fabric projects here, I find them very helpful and full of good tidbits of code and practices. Keep them coming :)

I have a question regarding how you inject the WatchDogService instance into the Web Api Controller by implementing IHttpControllerActivator in the OwinCommunicationListener class - this works great for a controller. But, I am trying to pass my stateful service instance into a custom OWIN middleware class in the same manner but haven't been able to figure this out. 

	public class MyCustomMiddleware : OwinMiddleware
	{
	    public MyCustomMiddleware(OwinMiddleware next) : base(next) { }
	
	    public async override Task Invoke(IOwinContext context)
	    {
	        // need access to stateful service instance here
	        ...

The reason for this is I have some metrics handling code in my stateful service class, and I want to be able to increment my metrics from the middleware. For example, call this method:
    
	public class MyStatefulService : StatefulService 
	{
	    public void IncrementMetric(string name) => _metrics[name]?.Increment();
	    ...
    
Do you know of a way to do this in SF? Thanks again and I really appreciate any direction you may have. Have a great evening!

Cheers, 
Rich

**Comment by toddabel** [comment]
This repo will be moving to the Azure-Samples at some point and the content of the readme will be an official article. I posted this here temporarily because I wanted to have it available while it goes through the MSFT processes to be published, so it will go away at some point. I'm not sure how to inject into the middleware.
